spring.application.name=gateway

server.port=8080

rabbitmq.management.host=${SPRING_RABBITMQ_HOST:rabbitmq}
rabbitmq.management.port=15672
rabbitmq.management.username=${SPRING_RABBITMQ_USERNAME:swift}
rabbitmq.management.password=${SPRING_RABBITMQ_PASSWORD:swift}
