spring.application.name=tracking-service

server.port=8082

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:swift}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:swift}
spring.rabbitmq.listener.simple.missing-queues-fatal=false

warehouse.capacity=${WAREHOUSE_CAPACITY:100}
app.timezone=${APP_TIMEZONE:Asia/Colombo}
app.source-event-timezone=${APP_SOURCE_EVENT_TIMEZONE:UTC}
app.ros-route-lookup-url=${ROS_ROUTE_LOOKUP_URL:http://ros-adapter:8084/api/ros/routes/{orderNumber}}
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=12MB
