spring.application.name=tracking-service

server.port=8082

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:swift}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:swift}
spring.rabbitmq.listener.simple.missing-queues-fatal=false

warehouse.capacity=${WAREHOUSE_CAPACITY:100}
