spring.application.name=wms-adapter

server.port=8085

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:swift}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:swift}
spring.rabbitmq.listener.simple.missing-queues-fatal=false

wms.tcp.host=${WMS_TCP_HOST:localhost}
wms.tcp.port=${WMS_TCP_PORT:9095}
wms.tcp.connect-timeout-ms=${WMS_TCP_CONNECT_TIMEOUT_MS:3000}
wms.tcp.read-timeout-ms=${WMS_TCP_READ_TIMEOUT_MS:5000}
